# Week 8 (Tue) - Class Activities in CS 315

You are given the file `netflix_top10_countries.tsv` in the folder data, solve the following tasks using it.

**Table of Contents**

1. [Q1: Load the file](#q1)
2. [Q2: Show number of rows](#q2)
3. [Q3: Show column names](#q3)
4. [Q4: Show number of total countries](#q4)
5. [Q5: Show number of TV series](#q5)
6. [Q6: Number of TV series in South Korea](#q6)
7. [Q7: Total weeks of Squid Games in Italy ](#q7)
8. [Q8: Time frame for a given country](#q8)
9. [Q9: Is number of weeks in ranking equal?](#q9)
10. [Q10: Country with fewest weeks](#q10)
11. [New Task](#nt)

<a id="q1"></a>
### Q1: Load the file

In [1]:
import pandas as pd

df=pd.read_csv("netflix_top10_countries.tsv", sep="\t")

In [2]:
df

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2026-10-18,Films,1,Therapy Done Right,NaN,1
1,Argentina,AR,2026-10-18,Films,2,Animals,NaN,2
2,Argentina,AR,2026-10-18,Films,3,Anyone But You,NaN,2
3,Argentina,AR,2026-10-18,Films,4,Doing Life,NaN,3
4,Argentina,AR,2026-10-18,Films,5,Ice Age: Collision Course,NaN,5
...,...,...,...,...,...,...,...,...
515915,Vietnam,VN,2021-07-04,TV,6,Reply 1988,Reply 1988: Season 1,1
515916,Vietnam,VN,2021-07-04,TV,7,"Nevertheless,","Nevertheless,: Limited Series",1
515917,Vietnam,VN,2021-07-04,TV,8,Too Hot to Handle,Too Hot to Handle: Season 2,1
515918,Vietnam,VN,2021-07-04,TV,9,Record of Ragnarok,Record of Ragnarok: Season 1,1
515919,Vietnam,VN,2021-07-04,TV,10,Crash Landing on You,Crash Landing on You: Limited Series,1

<a id="q2"></a>
### Q2: Show number of rows

In [3]:
len(df)

515920

<a id="q3"></a>
### Q3: Show column names

In [4]:
df.columns

Index(['country_name', 'country_iso2', 'week', 'category', 'weekly_rank',
       'show_title', 'season_title', 'cumulative_weeks_in_top_10'],
      dtype='str')

<a id="q4"></a>
### Q4: Show number of total countries

In [5]:
df["country_name"].nunique()

94

<a id="q5"></a>
### Q5: Show number of TV series

In [6]:
df["show_title"].nunique()

12283

<a id="q6"></a>
### Q6: Number of TV series in South Korea

In [7]:
df.loc[df["country_name"]=="South Korea", "show_title"].nunique()

1581

<a id="q7"></a>
### Q7: Total weeks of Squid Game in Italy

In [9]:
df.loc[df["country_name"]=="Italy"].loc[df["show_title"]=="Squid Game"].shape[0]

37

<a id="q8"></a>
### Q8: Time frame for a given country

Write a function that given a country name prints out the start and end date of their rankings.

Once you have created the function, call it for a few countries to test it.

In [10]:
def time_frame(country):
    weeks = df[df['country_name'] == country]['week']
    print(f"{country}: {weeks.min()} to {weeks.max()}")

for c in ['Russia', 'South Korea', 'Italy']:
    time_frame(c)

Russia: 2021-07-04 to 2022-02-27
South Korea: 2021-07-04 to 2026-10-18
Italy: 2021-07-04 to 2026-10-18

<a id="q9"></a>
### Q9: Is number of weeks equal for each country?

The total number of weeks in the rankings is `len(df['week'].unique())`.

The total number of countries is `len(df['country_name'].unique())`.  

For every week, each country has 20 rows.   

If they all stayed the same number of weeks, then the product of these three weeks would be the same as the total number of rows.

In [11]:
len(df['week'].unique()) * len(df['country_name'].unique()) * 20 == len(df)

False

We should have expected this to be `False` since we saw in Q8 that Russia stopped being in the rankings after it attacked Ukraine in February 2022.

<a id="q10"></a>
### Q10: Country with fewest weeks

Write a one-liner that will show the country with the fewest weeks in the Netflix rankings

In [12]:
df.groupby("country_name")["week"].nunique().idxmin()

'Russia'

<a id="nt"></a>
### New task: rank2score

In [13]:
# create a dictionary with rank as key and score as value. 
# call .get() to get the score corresponding to the rank
def rank2score(rank):
    points = {
        1: 25,
        2: 18,
        3: 15,
        4: 12,
        5: 10,
        6: 8,
        7: 6,
        8: 4,
        9: 2,
        10: 1
    }
    return points.get(rank, 0)

In [14]:
df["score"] = df["weekly_rank"].apply(rank2score)

In [ ]:
# keep only the useful columns using [[ ]]
df = df[["country_name", "week", "weekly_rank", "score", "show_title", "cumulative_weeks_in_top_10"]]
df

,country_name,week,weekly_rank,score,show_title,cumulative_weeks_in_top_10
0,Argentina,2026-10-18,1,25,Therapy Done Right,1
1,Argentina,2026-10-18,2,18,Animals,2
2,Argentina,2026-10-18,3,15,Anyone But You,2
3,Argentina,2026-10-18,4,12,Doing Life,3
4,Argentina,2026-10-18,5,10,Ice Age: Collision Course,5
...,...,...,...,...,...,...
515915,Vietnam,2021-07-04,6,8,Reply 1988,1
515916,Vietnam,2021-07-04,7,6,"Nevertheless,",1
515917,Vietnam,2021-07-04,8,4,Too Hot to Handle,1
515918,Vietnam,2021-07-04,9,2,Record of Ragnarok,1
515919,Vietnam,2021-07-04,10,1,Crash Landing on You,1

In [ ]:
# create a new df for When Life Gives You Tangerines
df2 = pd.DataFrame()
# calculate total scores grouped by countries
df2 = df.loc[df["show_title"]=="When Life Gives You Tangerines"].groupby("country_name")["score"].sum().reset_index(name="total_points")
# calculate total weeks and map it to the dataframe
weeks = df.loc[df["show_title"]=="When Life Gives You Tangerines"].groupby("country_name")["cumulative_weeks_in_top_10"].sum()
df2["total_weeks"] = df2["country_name"].map(weeks)
# list the rankings
rankingsList = df.loc[df["show_title"]=="When Life Gives You Tangerines"].groupby("country_name")["weekly_rank"].agg(list)
df2["rankings_list"] = df2["country_name"].map(rankingsList)
df2

,country_name,total_points,total_weeks,rankings_list
0,Argentina,10,3,"[8, 7]"
1,Bahrain,43,21,"[9, 6, 6, 6, 3, 9]"
2,Bangladesh,219,231,"[10, 10, 10, 10, 9, 7, 5, 3, 4, 6, 4, 4, 3, 3,..."
3,Bolivia,124,55,"[7, 7, 6, 6, 2, 2, 2, 2, 2, 7]"
4,Brazil,24,10,"[7, 7, 7, 7]"
5,Chile,73,45,"[10, 7, 10, 9, 4, 2, 4, 3, 7]"
6,Colombia,40,15,"[7, 6, 7, 5, 5]"
7,Costa Rica,38,15,"[5, 7, 4, 6, 9]"
8,Dominican Republic,11,10,"[8, 9, 10, 8]"
9,Ecuador,97,36,"[6, 7, 6, 3, 2, 3, 3, 4]"
10,Egypt,7,3,"[10, 7]"
11,El Salvador,104,55,"[10, 8, 7, 4, 4, 2, 3, 2, 4, 7]"
12,Guatemala,81,45,"[8, 7, 7, 4, 2, 4, 4, 5, 10]"
13,Honduras,92,45,"[9, 8, 4, 5, 2, 3, 3, 4, 8]"
14,Hong Kong,147,55,"[9, 7, 6, 4, 3, 2, 2, 2, 1, 1]"
15,India,156,105,"[8, 5, 7, 4, 3, 4, 5, 3, 3, 3, 4, 5, 2, 9]"
16,Indonesia,166,45,"[8, 6, 2, 2, 1, 2, 1, 1, 1]"
17,Japan,31,21,"[10, 5, 6, 9, 7, 8]"
18,Jordan,25,15,"[10, 8, 8, 8, 4]"
19,Kuwait,63,28,"[10, 10, 6, 5, 3, 2, 5]"
20,Malaysia,140,55,"[8, 9, 5, 3, 2, 2, 3, 2, 1, 3]"
21,Maldives,69,28,"[8, 7, 5, 4, 4, 5, 3]"
22,Mexico,74,45,"[10, 8, 8, 8, 3, 2, 5, 4, 7]"
23,Morocco,25,10,"[10, 7, 6, 5]"
24,Nicaragua,88,45,"[8, 8, 6, 5, 3, 3, 2, 4, 9]"
25,Nigeria,7,3,"[10, 7]"
26,Oman,72,45,"[10, 8, 5, 7, 4, 6, 4, 3, 8]"
27,Pakistan,100,78,"[9, 10, 9, 7, 6, 4, 4, 4, 5, 6, 4, 3]"
28,Panama,25,15,"[5, 7, 7, 9, 10]"
29,Paraguay,58,21,"[8, 4, 4, 4, 4, 7]"
30,Peru,158,78,"[10, 7, 5, 5, 5, 3, 1, 2, 3, 2, 2, 4]"
31,Philippines,161,45,"[10, 7, 2, 2, 1, 1, 1, 1, 2]"
32,Qatar,101,36,"[9, 5, 5, 2, 3, 2, 2, 5]"
33,Saudi Arabia,64,28,"[8, 6, 5, 6, 3, 2, 10]"
34,Singapore,107,55,"[10, 10, 9, 5, 4, 3, 3, 3, 2, 2]"
35,South Korea,185,105,"[8, 10, 9, 9, 6, 6, 6, 4, 3, 1, 1, 1, 1, 1]"
36,Sri Lanka,81,45,"[8, 6, 7, 7, 6, 4, 3, 4, 5]"
37,Taiwan,192,66,"[10, 7, 4, 4, 2, 1, 1, 1, 1, 1, 2]"
38,Thailand,132,45,"[10, 8, 6, 2, 2, 2, 1, 1, 3]"
39,Turkey,10,6,"[8, 9, 8]"
40,United Arab Emirates,72,36,"[10, 8, 7, 3, 5, 3, 3, 7]"
41,Venezuela,40,21,"[8, 5, 5, 5, 8, 9]"
42,Vietnam,170,55,"[8, 6, 5, 3, 2, 1, 1, 1, 1, 3]"